openapi: 3.0.3
info:
  title: Сервис Аренды - OpenAPI 3.0
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: Rent
    description: Работа с арендами
paths:
  /rent:
    post:
      tags:
        - Rent
      summary: Добавить новую аренду
      description: Добавить новую аренду
      operationId: AddRent
      parameters:
        - name: address
          in: query
          description: Адрес квартиры
          required: true
          schema:
            type: string
            format: string
        - name: cost
          in: query
          description: Стоимость аренды
          required: true
          schema:
            type: number
            format: double
        - name: status
          in: query
          description: статус аренды
          required: true
          schema:
            type: string
            enum:
              - Занята
              - Свободна
      responses:
        '200':
          description: Успешно добавлено
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      tags:
        - Rent
      summary: Посмотреть все
      description: Посмотреть все
      operationId: getAllRents
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rent'
  /rent/{rentId}:
    post:
      tags:
        - Rent
      summary: Добавить новую аренду с Id
      description: Добавить новую аренду с Id
      operationId: addWithID
      parameters:
        - name: rentId
          in: path
          description: ID аренды для добавления
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: данные аренды
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rent'
        required: true
      responses:
        '200':
          description: Успешно добавлено
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '409':
          description: Аренда с Id уже существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      tags:
        - Rent
      summary: Получить по Id
      description: Получить по Id
      operationId: gerRentById
      parameters:
        - name: rentId
          in: path
          description: ID аренды
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rent'
        '400':
          description: Некорректный Id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Аренда с Id не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    put:
      tags:
        - Rent
      summary: Изменить существующую аренду
      description: Изменить существующую аренду
      operationId: updateRent
      parameters:
        - name: rentId
          in: path
          description: ID
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Данные аренды
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rent'
        required: true
      responses:
        '200':
          description: Успешно
        '400':
          description: Некорректные данные
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Аренда не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    delete:
      tags:
        - Rent
      summary: Удалить аренду
      description: Удалить аренду
      operationId: deleteRent
      parameters:
        - name: rentId
          in: path
          description: Rent id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Некорректное значение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '404':
          description: Некорректное значение
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
components:
  schemas:
    Rent:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        cost:
          type: number
          format: double
          example: 198.772
        address:
          type: string
          example: Street 1
        status:
          type: string
          description: Rent Status
          example: Занята
          enum:
            - Занята
            - Свободна
    ErrorMessage:
      type: object
      properties:
        error:
          type: string
          format: string
        timestamp:
          type: string
          format: date-time